// =============================================================================
// 分类索引系统 - 快速本地匹配
// =============================================================================

// 中文关键词 → Danbooru 标签的映射索引
const CHINESE_INDEX = {
    // 发色
    '银发': ['silver_hair', 'grey_hair', 'white_hair', 'platinum_hair'],
    '白发': ['white_hair', 'silver_hair'],
    '黑发': ['black_hair'],
    '金发': ['blonde_hair', 'blond_hair'],
    '棕发': ['brown_hair'],
    '红发': ['red_hair'],
    '蓝发': ['blue_hair'],
    '粉发': ['pink_hair'],
    '紫发': ['purple_hair'],
    '绿发': ['green_hair'],
    '橙发': ['orange_hair'],
    '灰发': ['grey_hair', 'silver_hair'],
    '渐变发': ['gradient_hair', 'multicolored_hair'],
    '彩虹发': ['rainbow_hair'],
    
    // 发型
    '长发': ['long_hair', 'very_long_hair'],
    '短发': ['short_hair'],
    '双马尾': ['twintails'],
    '单马尾': ['ponytail', 'side_ponytail'],
    '刘海': ['bangs', 'blunt_bangs', 'side_bangs'],
    '呆毛': ['ahoge'],
    '卷发': ['curly_hair'],
    '波浪发': ['wavy_hair'],
    '直发': ['straight_hair'],
    '姬发式': ['hime_cut'],
    '丸子头': ['hair_bun'],
    '编发': ['braided_hair'],
    '三股辫': ['triple_braid'],
    '侧马尾': ['side_ponytail'],
    '散发': ['hair_down'],
    '半扎发': ['half_updo'],
    '散发': ['hair_flaps'],
    '齐刘海': ['blunt_bangs'],
    '斜刘海': ['side_bangs'],
    '过眉刘海': ['eye_covers'],
    'M 字刘海': ['m-shaped_bangs'],
    '空气刘海': ['see-through_bangs'],
    '公主切': ['hime_cut'],
    '猫耳': ['cat_ears', 'nekomimi'],
    '狐耳': ['fox_ears', 'kitsune_ears'],
    '狼耳': ['wolf_ears'],
    '兔耳': ['rabbit_ears', 'bunny_ears'],
    '熊耳': ['bear_ears'],
    '鼠耳': ['mouse_ears'],
    '犬耳': ['dog_ears'],
    '马耳': ['horse_ears'],
    '龙耳': ['dragon_ears'],
    '兽耳': ['animal_ears'],
    '翅膀': ['wings', 'fairy_wings', 'butterfly_wings', 'dragon_wings', 'angel_wings', 'demon_wings', 'bat_wings'],
    '天使翅膀': ['angel_wings', 'feathered_wings'],
    '恶魔翅膀': ['demon_wings', 'bat_wings'],
    '蝴蝶翅膀': ['butterfly_wings'],
    '龙翼': ['dragon_wings'],
    '尾巴': ['tail', 'animal_tail'],
    '猫尾': ['cat_tail'],
    '狐尾': ['fox_tail'],
    '龙尾': ['dragon_tail'],
    '恶魔尾': ['demon_tail'],
    '尾巴': ['tail'],
    '角': ['horns', 'demon_horns', 'dragon_horns', 'oni_horns', 'antlers'],
    '恶魔角': ['demon_horns'],
    '龙角': ['dragon_horns'],
    '鬼角': ['oni_horns'],
    '鹿角': ['antlers'],
    '独角': ['horn'],
    
    // 瞳色
    '蓝眼': ['blue_eyes', 'light_blue_eyes', 'dark_blue_eyes'],
    '红眼': ['red_eyes'],
    '绿眼': ['green_eyes'],
    '紫眼': ['purple_eyes'],
    '黄眼': ['yellow_eyes', 'golden_eyes'],
    '金眼': ['golden_eyes', 'yellow_eyes'],
    '黑眼': ['black_eyes'],
    '棕眼': ['brown_eyes'],
    '粉眼': ['pink_eyes'],
    '异色瞳': ['heterochromia', 'heterochromatic'],
    '多色瞳': ['multicolored_eyes'],
    '红蓝瞳': ['red_and_blue_eyes'],
    '星星眼': ['star-shaped_pupils', 'star_eyes'],
    '心形眼': ['heart-shaped_pupils'],
    '十字眼': ['cross-shaped_pupils'],
    '螺旋眼': ['spiral_pupils'],
    '空洞眼': ['empty_eyes', 'hollow_eyes'],
    '发光眼': ['glowing_eyes'],
    '闭眼': ['closed_eyes'],
    '半闭眼': ['half-closed_eyes'],
    '眯眼': ['narrowed_eyes'],
    '含泪': ['tearing_up', 'tears'],
    '哭': ['crying'],
    '笑': ['smile', 'grin', 'laughing'],
    '微笑': ['smile'],
    '大笑': ['laughing', 'big_smile'],
    '邪笑': ['smirk', 'evil_smile'],
    '坏笑': ['smirk'],
    '生气': ['angry', 'annoyed'],
    '惊讶': ['surprised', 'shocked'],
    '害怕': ['scared', 'fearful'],
    '害羞': ['blush', 'embarrassed'],
    '脸红': ['blush'],
    '困': ['sleepy', 'drowsy'],
    '晕': ['dizzy', 'confused'],
    '翻白眼': ['rolling_eyes'],
    ' wink': ['wince', 'wink'],
    '眨眼': ['wink'],
    
    // 服装
    '校服': ['school_uniform', 'sailor_uniform', 'serafuku'],
    '水手服': ['sailor_collar', 'sailor_uniform', 'serafuku'],
    '水手领': ['sailor_collar'],
    '女仆装': ['maid', 'maid_apron', 'french_maid'],
    '和服': ['kimono', 'yukata', 'furisode'],
    '浴衣': ['yukata'],
    '振袖': ['furisode'],
    '连衣裙': ['dress'],
    '裙子': ['skirt', 'miniskirt', 'pleated_skirt'],
    '短裙': ['miniskirt'],
    '百褶裙': ['pleated_skirt'],
    '衬衫': ['shirt', 'collared_shirt'],
    'T 恤': ['t-shirt'],
    '毛衣': ['sweater', 'turtleneck'],
    '高领毛衣': ['turtleneck'],
    '夹克': ['jacket'],
    '外套': ['coat', 'jacket'],
    '西装': ['suit', 'blazer'],
    '领带': ['necktie', 'bowtie'],
    '蝴蝶结': ['bow', 'hair_ribbon', 'ribbon'],
    '丝带': ['ribbon'],
    '发带': ['hairband', 'hair_ribbon'],
    '发夹': ['hairclip', 'hair_ornament'],
    '帽子': ['hat', 'beret', 'witch_hat', 'santa_hat'],
    '贝雷帽': ['beret'],
    '巫师帽': ['witch_hat'],
    '圣诞帽': ['santa_hat'],
    '围巾': ['scarf'],
    '手套': ['gloves', 'fingerless_gloves'],
    '露指手套': ['fingerless_gloves'],
    '过膝袜': ['thighhighs'],
    '连裤袜': ['pantyhose', 'tights'],
    '丝袜': ['pantyhose'],
    '袜子': ['socks', 'ankle_socks'],
    '短袜': ['ankle_socks'],
    '裸足': ['barefoot', 'bare_legs'],
    '赤脚': ['barefoot'],
    '鞋子': ['shoes', 'sneakers', 'boots', 'sandals'],
    '靴子': ['boots', 'thigh_boots', 'knee_boots'],
    '长靴': ['thigh_boots'],
    '凉鞋': ['sandals'],
    '高跟鞋': ['high_heels'],
    '泳衣': ['swimsuit', 'bikini', 'school_swimsuit', 'one-piece_swimsuit'],
    '比基尼': ['bikini'],
    '死库水': ['school_swimsuit'],
    '连体泳衣': ['one-piece_swimsuit'],
    '内衣': ['lingerie', 'bra', 'panties'],
    '胸罩': ['bra'],
    '内裤': ['panties'],
    '睡衣': ['nightgown', 'pajamas'],
    '婚纱': ['wedding_dress'],
    '盔甲': ['armor', 'plate_armor', 'chainmail'],
    '板甲': ['plate_armor'],
    '锁子甲': ['chainmail'],
    '披风': ['cape', 'cloak'],
    '斗篷': ['cloak', 'cape'],
    '兜帽': ['hood', 'hooded_cloak'],
    '眼镜': ['glasses', 'eyeglasses', 'sunglasses'],
    '墨镜': ['sunglasses'],
    '眼罩': ['eyepatch', 'blindfold'],
    '面具': ['mask'],
    '项链': ['necklace', 'choker', 'pendant'],
    '项圈': ['choker', 'collar'],
    '手环': ['bracelet'],
    '戒指': ['ring'],
    '耳环': ['earrings'],
    '头饰': ['hair_ornament', 'tiara', 'crown', 'flower_in_hair'],
    '皇冠': ['crown', 'tiara'],
    '花饰': ['flower_in_hair'],
    '铃铛': ['bell', 'cowbell'],
    '纹身': ['tattoo'],
    '创可贴': ['bandaid'],
    '绷带': ['bandage'],
    '机械': ['mechanical', 'cyborg', 'robot', 'android'],
    '机器人': ['robot', 'android'],
    '义肢': ['prosthetic'],
    '机械臂': ['mechanical_arms'],
    '机械腿': ['mechanical_legs'],
    '机械耳': ['mechanical_ears'],
    
    // 姿势
    '站立': ['standing'],
    '坐着': ['sitting'],
    '跪坐': ['seiza', 'kneeling'],
    '躺': ['lying'],
    '趴': ['prone'],
    '侧躺': ['lying_on_side'],
    '叉腰': ['hand_on_hip'],
    '举手': ['arms_up', 'raised_arms'],
    '双手举': ['arms_up'],
    '单手举': ['one_arm_up'],
    '双手背后': ['arms_behind_back'],
    '手托脸颊': ['hand_on_own_cheek'],
    '托腮': ['hand_on_own_cheek'],
    '手指交叉': ['interlocked_fingers'],
    '十指相扣': ['interlocked_fingers'],
    '剪刀手': ['v', 'peace_sign'],
    '和平手势': ['peace_sign'],
    '比心': ['heart'],
    '指人': ['pointing'],
    '回头': ['looking_back'],
    '看向观众': ['looking_at_viewer'],
    '侧视': ['looking_to_the_side'],
    '俯视': ['looking_down'],
    '仰视': ['looking_up'],
    '闭眼': ['closed_eyes'],
    '歪头': ['head_tilt', 'tilting_head'],
    '倾斜': ['leaning'],
    '靠': ['leaning'],
    '抱膝': ['hugging_own_legs'],
    '抱臂': ['arms_crossed'],
    '双手合十': ['hands_together'],
    '祈祷': ['praying'],
    '跳跃': ['jumping'],
    '跑': ['running'],
    '走': ['walking'],
    '飞': ['flying'],
    '漂浮': ['floating'],
    '跳舞': ['dancing'],
    '唱歌': ['singing'],
    '弹吉他': ['playing_instrument', 'playing_guitar'],
    '弹钢琴': ['playing_instrument', 'playing_piano'],
    '画画': ['painting', 'drawing'],
    '看书': ['reading'],
    '写字': ['writing'],
    '做饭': ['cooking'],
    '吃饭': ['eating'],
    '喝茶': ['drinking', 'tea'],
    '喝酒': ['drinking', 'alcohol'],
    '睡觉': ['sleeping'],
    '洗澡': ['bathing', 'shower'],
    '泡澡': ['bath'],
    '游泳': ['swimming'],
    '战斗': ['fighting', 'battle'],
    '施法': ['casting_spell', 'magic'],
    '拔剑': ['drawing_sword'],
    '持剑': ['holding_sword'],
    '持枪': ['holding_gun'],
    '持弓': ['holding_bow'],
    '持法杖': ['holding_staff'],
    '骑马': ['horseback_riding'],
    '骑车': ['bicycle', 'riding'],
    
    // 背景/场景
    '户外': ['outdoors'],
    '室内': ['indoors'],
    '天空': ['sky'],
    '云': ['cloud', 'cloudy_sky'],
    '晴天': ['clear_sky', 'sunny'],
    '阴天': ['cloudy'],
    '雨天': ['rain', 'rainy'],
    '雪天': ['snow', 'snowing'],
    '夜晚': ['night', 'night_sky'],
    '白天': ['day'],
    '黄昏': ['sunset', 'dusk'],
    '黎明': ['sunrise', 'dawn'],
    '月亮': ['moon', 'crescent_moon', 'full_moon'],
    '星星': ['stars', 'starry_sky', 'star'],
    '银河': ['milky_way'],
    '彩虹': ['rainbow'],
    '太阳': ['sun', 'sunlight'],
    '阳光': ['sunlight'],
    '月光': ['moonlight'],
    '樱花': ['cherry_blossoms', 'cherry_tree'],
    '花': ['flower', 'flowers'],
    '玫瑰': ['rose'],
    '百合': ['lily'],
    '向日葵': ['sunflower'],
    '树': ['tree'],
    '森林': ['forest'],
    '草地': ['grass', 'meadow'],
    '花园': ['garden'],
    '公园': ['park'],
    '山': ['mountain'],
    '山丘': ['hill'],
    '悬崖': ['cliff'],
    '洞穴': ['cave'],
    '海滩': ['beach', 'ocean', 'sea'],
    '海洋': ['ocean', 'sea'],
    '湖': ['lake'],
    '河流': ['river'],
    '瀑布': ['waterfall'],
    '沙漠': ['desert'],
    '雪地': ['snow', 'snowy'],
    '冰': ['ice'],
    '城市': ['city', 'urban'],
    '街道': ['street', 'cityscape'],
    '建筑': ['building'],
    '学校': ['school', 'schoolyard'],
    '教室': ['classroom'],
    '图书馆': ['library'],
    '教堂': ['church', 'cathedral'],
    '城堡': ['castle'],
    '宫殿': ['palace'],
    '废墟': ['ruins'],
    '房间': ['room'],
    '卧室': ['bedroom'],
    '浴室': ['bathroom'],
    '厨房': ['kitchen'],
    '客厅': ['living_room'],
    '咖啡馆': ['cafe'],
    '餐厅': ['restaurant'],
    '商店': ['store', 'shop'],
    '医院': ['hospital'],
    '墓地': ['graveyard'],
    '神社': ['shrine'],
    '寺庙': ['temple'],
    '塔': ['tower'],
    '桥': ['bridge'],
    '窗户': ['window'],
    '门': ['door'],
    '楼梯': ['stairs', 'staircase'],
    '阳台': ['balcony'],
    '屋顶': ['rooftop'],
    '地下室': ['basement'],
    '走廊': ['corridor', 'hallway'],
    '电梯': ['elevator'],
    '地铁': ['subway', 'train'],
    '火车': ['train'],
    '汽车': ['car'],
    '自行车': ['bicycle'],
    '飞机': ['airplane'],
    '船': ['ship', 'boat'],
    '宇宙': ['space', 'universe'],
    '太空': ['space'],
    '水下': ['underwater'],
    '火焰': ['fire', 'flames'],
    '水': ['water'],
    '风': ['wind'],
    '雷电': ['lightning', 'thunder'],
    '魔法阵': ['magic_circle'],
    '符文': ['rune'],
    '结界': ['barrier'],
    '传送门': ['portal'],
    '镜子': ['mirror'],
    '水面': ['reflection', 'water_reflection'],
    '影子': ['shadow'],
    '光': ['light', 'light_ray', 'sunlight', 'moonlight'],
    '光柱': ['light_ray', 'god_rays'],
    '丁达尔': ['light_ray', 'god_rays'],
    '体积光': ['light_ray'],
    '逆光': ['backlighting'],
    '轮廓光': ['rim_lighting'],
    '侧光': ['side_lighting'],
    '柔光': ['soft_lighting'],
    '硬光': ['hard_lighting'],
    '霓虹灯': ['neon', 'neon_lights'],
    '灯光': ['lamp', 'light_bulb'],
    '蜡烛': ['candle'],
    '萤火虫': ['firefly'],
    '蝴蝶': ['butterfly'],
    '鸟': ['bird'],
    '猫': ['cat'],
    '狗': ['dog'],
    '兔子': ['rabbit', 'bunny'],
    '狐狸': ['fox'],
    '狼': ['wolf'],
    '龙': ['dragon'],
    '蛇': ['snake'],
    '鱼': ['fish'],
    '鲸鱼': ['whale'],
    '海豚': ['dolphin'],
    '马': ['horse'],
    '鹿': ['deer'],
    '熊': ['bear'],
    '老虎': ['tiger'],
    '狮子': ['lion'],
    '豹': ['leopard', 'panther'],
    '羊': ['sheep', 'goat'],
    '牛': ['cow', 'bull'],
    '猪': ['pig'],
    '鸡': ['chicken', 'rooster'],
    '鸭': ['duck'],
    '鹅': ['goose'],
    '鸽子': ['pigeon'],
    '乌鸦': ['crow'],
    '猫头鹰': ['owl'],
    '鹰': ['eagle', 'hawk'],
    '鹦鹉': ['parrot'],
    '孔雀': ['peacock'],
    '天鹅': ['swan'],
    '企鹅': ['penguin'],
    '青蛙': ['frog'],
    '乌龟': ['turtle'],
    '蜥蜴': ['lizard'],
    '鳄鱼': ['crocodile', 'alligator'],
    '蜘蛛': ['spider'],
    '蜜蜂': ['bee'],
    '蝴蝶': ['butterfly'],
    '蛾': ['moth'],
    '蚂蚁': ['ant'],
    '瓢虫': ['ladybug'],
    '甲虫': ['beetle'],
    '螳螂': ['mantis'],
    '蜗牛': ['snail'],
    '章鱼': ['octopus'],
    '乌贼': ['squid'],
    '水母': ['jellyfish'],
    '海星': ['starfish'],
    '珊瑚': ['coral'],
    '贝壳': ['seashell'],
    '珍珠': ['pearl'],
    '宝石': ['gem', 'gemstone', 'diamond', 'ruby', 'sapphire', 'emerald'],
    '钻石': ['diamond'],
    '红宝石': ['ruby'],
    '蓝宝石': ['sapphire'],
    '翡翠': ['emerald', 'jade'],
    '水晶': ['crystal'],
    '魔法石': ['magic_stone'],
    '灵石': ['spirit_stone'],
    '魂石': ['soul_stone'],
    '魔石': ['magic_stone'],
    '武器': ['weapon', 'sword', 'dagger', 'axe', 'spear', 'bow', 'arrow', 'gun', 'pistol', 'rifle', 'staff', 'wand', 'hammer', 'mace', 'scythe', 'whip', 'chainsaw', 'knife'],
    '剑': ['sword', 'katana', 'broadsword', 'rapier'],
    '刀': ['sword', 'katana', 'knife'],
    '武士刀': ['katana'],
    '匕首': ['dagger'],
    '斧': ['axe'],
    '枪': ['spear', 'lance', 'gun', 'rifle'],
    '弓': ['bow'],
    '箭': ['arrow'],
    '法杖': ['staff', 'wand'],
    '魔杖': ['wand'],
    '锤子': ['hammer', 'mace'],
    '镰刀': ['scythe'],
    '鞭子': ['whip'],
    '电锯': ['chainsaw'],
    '盾牌': ['shield'],
    '炸弹': ['bomb', 'explosion'],
    '手榴弹': ['grenade'],
    '火箭筒': ['rocket_launcher'],
    '魔法书': ['spellbook', 'magic_book'],
    '书': ['book'],
    '卷轴': ['scroll'],
    '药瓶': ['potion'],
    '药水': ['potion'],
    '食物': ['food', 'bread', 'cake', 'cookie', 'apple', 'orange', 'banana', 'grape', 'strawberry', 'cherry', 'watermelon', 'pizza', 'burger', 'sandwich', 'rice', 'noodles', 'sushi', 'candy', 'chocolate', 'ice_cream', 'lollipop'],
    '面包': ['bread'],
    '蛋糕': ['cake'],
    '饼干': ['cookie'],
    '苹果': ['apple'],
    '橙子': ['orange'],
    '香蕉': ['banana'],
    '葡萄': ['grape'],
    '草莓': ['strawberry'],
    '樱桃': ['cherry'],
    '西瓜': ['watermelon'],
    '披萨': ['pizza'],
    '汉堡': ['burger'],
    '三明治': ['sandwich'],
    '米饭': ['rice'],
    '面条': ['noodles', 'ramen', 'soba', 'udon'],
    '拉面': ['ramen'],
    '荞麦面': ['soba'],
    '乌冬面': ['udon'],
    '寿司': ['sushi'],
    '糖果': ['candy'],
    '巧克力': ['chocolate'],
    '冰淇淋': ['ice_cream'],
    '棒棒糖': ['lollipop'],
    '饮料': ['drink', 'beverage', 'tea', 'coffee', 'juice', 'milk', 'water', 'soda', 'beer', 'wine', 'sake', 'cocktail'],
    '茶': ['tea'],
    '咖啡': ['coffee'],
    '果汁': ['juice'],
    '牛奶': ['milk'],
    '水': ['water'],
    '汽水': ['soda'],
    '啤酒': ['beer'],
    '酒': ['wine', 'alcohol', 'sake'],
    '清酒': ['sake'],
    '鸡尾酒': ['cocktail'],
    '乐器': ['instrument', 'guitar', 'piano', 'violin', 'drum', 'flute', 'harp', 'saxophone', 'trumpet', 'cello', 'bass'],
    '吉他': ['guitar'],
    '钢琴': ['piano'],
    '小提琴': ['violin'],
    '鼓': ['drum'],
    '笛子': ['flute'],
    '竖琴': ['harp'],
    '萨克斯': ['saxophone'],
    '小号': ['trumpet'],
    '大提琴': ['cello'],
    '贝斯': ['bass'],
    '相机': ['camera'],
    '手机': ['cellphone', 'smartphone'],
    '电脑': ['computer', 'laptop'],
    '笔记本': ['laptop', 'notebook'],
    '平板': ['tablet'],
    '游戏机': ['game_console', 'handheld_game_console'],
    '游戏手柄': ['game_controller'],
    '耳机': ['headphones', 'earphones'],
    '麦克风': ['microphone'],
    '画笔': ['paintbrush'],
    '调色板': ['palette'],
    '颜料': ['paint'],
    '画布': ['canvas'],
    '画架': ['easel'],
    '伞': ['umbrella'],
    '阳伞': ['parasol'],
    '折扇': ['folding_fan'],
    '团扇': ['round_fan'],
    '灯笼': ['lantern'],
    '风筝': ['kite'],
    '气球': ['balloon'],
    '丝带': ['ribbon'],
    '彩带': ['streamer'],
    '彩纸': ['confetti'],
    '烟花': ['fireworks'],
    '烟火': ['fireworks'],
    '雪花': ['snowflake'],
    '雨滴': ['raindrops'],
    '水滴': ['water_drop'],
    '气泡': ['bubble', 'bubbles'],
    '肥皂泡': ['soap_bubbles'],
    '蒸汽': ['steam'],
    '烟雾': ['smoke'],
    '雾': ['fog', 'mist'],
    '云': ['cloud'],
    '彩虹': ['rainbow'],
    '极光': ['aurora'],
    '流星': ['shooting_star', 'meteor'],
    '彗星': ['comet'],
    '行星': ['planet'],
    '星球': ['planet'],
    '卫星': ['satellite', 'moon'],
    '空间站': ['space_station'],
    '火箭': ['rocket'],
    '飞船': ['spaceship'],
    'UFO': ['ufo'],
    '时钟': ['clock'],
    '怀表': ['pocket_watch'],
    '沙漏': ['hourglass'],
    '日历': ['calendar'],
    '地图': ['map'],
    '指南针': ['compass'],
    '望远镜': ['telescope'],
    '显微镜': ['microscope'],
    '放大镜': ['magnifying_glass'],
    '钥匙': ['key'],
    '锁': ['lock'],
    '门': ['door'],
    '窗': ['window'],
    '窗帘': ['curtain'],
    '地毯': ['carpet', 'rug'],
    '沙发': ['sofa', 'couch'],
    '椅子': ['chair'],
    '桌子': ['table', 'desk'],
    '床': ['bed'],
    '枕头': ['pillow'],
    '被子': ['blanket', 'quilt'],
    '床单': ['sheet'],
    '衣柜': ['wardrobe', 'closet'],
    '书架': ['bookshelf'],
    '花瓶': ['vase'],
    '镜子': ['mirror'],
    '画框': ['picture_frame'],
    '照片': ['photo', 'photograph'],
    '相框': ['photo_frame'],
    '雕塑': ['statue', 'sculpture'],
    '喷泉': ['fountain'],
    '雕像': ['statue'],
    '墓碑': ['tombstone', 'grave'],
    '十字架': ['cross'],
    '教堂': ['church'],
    '钟楼': ['clock_tower'],
    '灯塔': ['lighthouse'],
    '风车': ['windmill'],
    '水车': ['watermill'],
    '摩天轮': ['ferris_wheel'],
    '过山车': ['roller_coaster'],
    '旋转木马': ['carousel'],
    '游乐园': ['amusement_park'],
    '马戏团': ['circus'],
    '舞台': ['stage'],
    '幕布': ['curtain'],
    '聚光灯': ['spotlight'],
    '霓虹': ['neon'],
    '招牌': ['sign', 'signage'],
    '广告牌': ['billboard'],
    '旗帜': ['flag', 'banner'],
    '横幅': ['banner'],
    '彩旗': ['bunting'],
    '灯笼': ['lantern'],
    '蜡烛': ['candle'],
    '烛台': ['candlestick'],
    '香炉': ['incense_burner'],
    '香': ['incense'],
    '花环': ['wreath', 'garland'],
    '花束': ['bouquet'],
    '花篮': ['flower_basket'],
    '盆栽': ['potted_plant'],
    '仙人掌': ['cactus'],
    '多肉': ['succulent'],
    '蘑菇': ['mushroom'],
    '藤蔓': ['vine', 'vines'],
    '树叶': ['leaves'],
    '枫叶': ['maple_leaf'],
    '银杏叶': ['ginkgo_leaf'],
    '松针': ['pine_needles'],
    '苔藓': ['moss'],
    '蕨类': ['fern'],
    '竹子': ['bamboo'],
    '芦苇': ['reed'],
    '稻草': ['straw'],
    '干草': ['hay'],
    '麦穗': ['wheat', 'wheat_ear'],
    '稻谷': ['rice_plant'],
    '棉花': ['cotton'],
    '麻': ['hemp'],
    '丝绸': ['silk'],
    '缎': ['satin'],
    '蕾丝': ['lace'],
    '薄纱': ['tulle', 'sheer'],
    '雪纺': ['chiffon'],
    '天鹅绒': ['velvet'],
    '毛皮': ['fur'],
    '皮革': ['leather'],
    '牛仔布': ['denim'],
    '帆布': ['canvas'],
    '麻布': ['burlap', 'linen'],
    '粗呢': ['tweed'],
    '格纹': ['plaid', 'checkered'],
    '条纹': ['striped', 'stripes'],
    '波点': ['polka_dot'],
    '碎花': ['floral_print'],
    '迷彩': ['camouflage'],
    '豹纹': ['leopard_print'],
    '斑马纹': ['zebra_print'],
    '蛇纹': ['snake_print'],
    '虎纹': ['tiger_print'],
    '心形图案': ['heart_print'],
    '星星图案': ['star_print'],
    '月亮图案': ['moon_print'],
    '太阳图案': ['sun_print'],
    '云朵图案': ['cloud_print'],
    '彩虹图案': ['rainbow_print'],
    '火焰图案': ['fire_print'],
    '水波图案': ['water_print'],
    '雷电图案': ['lightning_print'],
    '雪花图案': ['snow_print'],
    '树叶图案': ['leaf_print'],
    '花朵图案': ['flower_print'],
    '动物图案': ['animal_print'],
    '文字图案': ['text_print', 'letter_print'],
    '数字图案': ['number_print'],
    '几何图案': ['geometric_print'],
    '抽象图案': ['abstract_print'],
    '渐变': ['gradient'],
    '彩虹渐变': ['rainbow_gradient'],
    '火焰渐变': ['fire_gradient'],
    '星空渐变': ['star_gradient'],
    '海洋渐变': ['ocean_gradient'],
    '森林渐变': ['forest_gradient'],
    '沙漠渐变': ['desert_gradient'],
    '极光渐变': ['aurora_gradient'],
    '霓虹渐变': ['neon_gradient'],
    '金属': ['metal', 'metallic'],
    '金色': ['gold', 'golden'],
    '银色': ['silver', 'silver_hair'],
    '铜色': ['copper', 'copper_hair'],
    '青铜色': ['bronze'],
    '玫瑰金': ['rose_gold'],
    '铂金': ['platinum'],
    '钛金': ['titanium'],
    '不锈钢': ['stainless_steel'],
    '铁': ['iron'],
    '钢': ['steel'],
    '铝': ['aluminum'],
    '铅': ['lead'],
    '锡': ['tin'],
    '锌': ['zinc'],
    '镍': ['nickel'],
    '铬': ['chrome'],
    '钨': ['tungsten'],
    '汞': ['mercury'],
    '铀': ['uranium'],
    '钚': ['plutonium'],
    '放射性': ['radioactive'],
    '核': ['nuclear', 'atom'],
    '原子': ['atom'],
    '分子': ['molecule'],
    '细胞': ['cell'],
    'DNA': ['dna'],
    'RNA': ['rna'],
    '基因': ['gene'],
    '染色体': ['chromosome'],
    '病毒': ['virus'],
    '细菌': ['bacteria'],
    '真菌': ['fungus', 'mushroom'],
    '寄生虫': ['parasite'],
    '昆虫': ['insect', 'bug'],
    '节肢动物': ['arthropod'],
    '甲壳类': ['crustacean'],
    '软体动物': ['mollusk'],
    '脊椎动物': ['vertebrate'],
    '哺乳动物': ['mammal'],
    '鸟类': ['bird'],
    '爬行动物': ['reptile'],
    '两栖动物': ['amphibian'],
    '鱼类': ['fish'],
    '无脊椎动物': ['invertebrate'],
    '植物': ['plant', 'flora'],
    '动物': ['animal', 'fauna'],
    '生物': ['creature', 'organism'],
    '生命': ['life'],
    '死亡': ['death', 'dead'],
    '灵魂': ['soul', 'ghost', 'spirit'],
    '幽灵': ['ghost', 'spirit'],
    '精灵': ['fairy', 'elf', 'spirit'],
    '仙子': ['fairy'],
    '妖精': ['fairy', 'goblin'],
    '小妖精': ['goblin'],
    '地精': ['goblin', 'dwarf'],
    '矮人': ['dwarf'],
    '巨人': ['giant', 'titan'],
    '泰坦': ['titan'],
    '神': ['god', 'deity', 'divine'],
    '神明': ['deity', 'god'],
    '女神': ['goddess'],
    '天使': ['angel'],
    '堕天使': ['fallen_angel'],
    '恶魔': ['demon', 'devil'],
    '魔鬼': ['devil'],
    '撒旦': ['satan'],
    '路西法': ['lucifer'],
    '吸血鬼': ['vampire'],
    '狼人': ['werewolf'],
    '僵尸': ['zombie'],
    '丧尸': ['zombie'],
    '骷髅': ['skeleton'],
    '木乃伊': ['mummy'],
    '科学怪人': ['frankensteins_monster'],
    '弗兰肯斯坦': ['frankensteins_monster'],
    '人偶': ['doll', 'puppet', 'marionette'],
    '木偶': ['puppet', 'marionette'],
    '提线木偶': ['marionette'],
    '机器人': ['robot', 'android', 'mecha'],
    '机甲': ['mecha', 'mech'],
    '机甲战士': ['mecha_pilot'],
    '驾驶员': ['pilot'],
    '飞行员': ['pilot'],
    '宇航员': ['astronaut'],
    '太空人': ['astronaut'],
    '潜水员': ['diver'],
    '消防员': ['firefighter'],
    '警察': ['police', 'police_officer'],
    '军人': ['military', 'soldier'],
    '士兵': ['soldier'],
    '骑士': ['knight'],
    '武士': ['samurai'],
    '忍者': ['ninja'],
    '刺客': ['assassin'],
    '猎人': ['hunter'],
    '魔法师': ['mage', 'wizard', 'witch', 'sorcerer', 'sorceress', 'enchanter', 'enchantress'],
    '法师': ['mage', 'wizard'],
    '男巫': ['wizard'],
    '女巫': ['witch'],
    '术士': ['warlock', 'sorcerer'],
    '牧师': ['priest', 'cleric'],
    '修女': ['nun'],
    '僧侣': ['monk'],
    '道士': ['taoist_priest'],
    '祭司': ['priest'],
    '萨满': ['shaman'],
    '德鲁伊': ['druid'],
    '炼金术士': ['alchemist'],
    '学者': ['scholar'],
    '老师': ['teacher'],
    '学生': ['student'],
    '医生': ['doctor', 'nurse'],
    '护士': ['nurse'],
    '厨师': ['chef', 'cook'],
    '服务员': ['waiter', 'waitress'],
    '女仆': ['maid'],
    '管家': ['butler'],
    '司机': ['driver'],
    '司机': ['chauffeur'],
    '秘书': ['secretary'],
    '老板': ['boss', 'executive'],
    '总裁': ['executive', 'ceo'],
    'CEO': ['ceo'],
    '经理': ['manager'],
    '总监': ['director'],
    '艺术家': ['artist'],
    '画家': ['painter'],
    '音乐家': ['musician'],
    '歌手': ['singer'],
    '演员': ['actor', 'actress'],
    '偶像': ['idol'],
    '明星': ['star', 'celebrity'],
    '名人': ['celebrity'],
    '网红': ['influencer'],
    '博主': ['blogger', 'vlogger'],
    'UP 主': ['uploader', 'content_creator'],
    '主播': ['streamer'],
    '玩家': ['gamer', 'player'],
    '游戏玩家': ['gamer'],
    '电竞选手': ['esports_player'],
    '职业选手': ['professional_player'],
    '运动员': ['athlete'],
    '跑步者': ['runner'],
    '游泳者': ['swimmer'],
    '骑行者': ['cyclist'],
    '登山者': ['climber'],
    '滑雪者': ['skier'],
    '滑冰者': ['skater'],
    '滑板': ['skateboard', 'skating'],
    '冲浪者': ['surfer'],
    '潜水者': ['diver'],
    '钓鱼者': ['fisher'],
    '农夫': ['farmer'],
    '渔民': ['fisherman'],
    '猎人': ['hunter'],
    '矿工': ['miner'],
    '伐木工': ['lumberjack'],
    '建筑工': ['construction_worker'],
    '机械师': ['mechanic'],
    '电工': ['electrician'],
    '水管工': ['plumber'],
    '木匠': ['carpenter'],
    '石匠': ['stonemason'],
    '铁匠': ['blacksmith'],
    '锻造师': ['smith'],
    '工匠': ['artisan', 'craftsman'],
    '发明家': ['inventor'],
    '科学家': ['scientist'],
    '工程师': ['engineer'],
    '程序员': ['programmer', 'coder', 'developer'],
    '黑客': ['hacker'],
    '侦探': ['detective'],
    '间谍': ['spy', 'agent'],
    '特工': ['agent', 'secret_agent'],
    '杀手': ['hitman', 'assassin'],
    '罪犯': ['criminal'],
    '囚犯': ['prisoner'],
    '犯人': ['criminal', 'prisoner'],
    '国王': ['king'],
    '女王': ['queen'],
    '王子': ['prince'],
    '公主': ['princess'],
    '皇帝': ['emperor'],
    '女皇': ['empress'],
    '太子': ['crown_prince'],
    '太子妃': ['crown_princess'],
    '贵族': ['noble', 'aristocrat'],
    '公爵': ['duke'],
    '侯爵': ['marquis'],
    '伯爵': ['count', 'earl'],
    '子爵': ['viscount'],
    '男爵': ['baron'],
    '领主': ['lord', 'feudal_lord'],
    '大臣': ['minister'],
    '将军': ['general'],
    '元帅': ['marshal'],
    '统帅': ['commander'],
    '指挥官': ['commander'],
    '队长': ['captain'],
    '队长': ['team_captain'],
    '首领': ['leader', 'chief'],
    '族长': ['clan_leader', 'tribal_chief'],
    '村长': ['village_chief'],
    '长老': ['elder'],
    '智者': ['sage', 'wise_man'],
    '先知': ['prophet', 'seer'],
    '占卜师': ['fortune_teller'],
    '算命先生': ['fortune_teller'],
    '塔罗师': ['tarot_reader'],
    '星象师': ['astrologer'],
    '占星师': ['astrologer'],
    '风水师': ['feng_shui_master'],
    '阴阳师': ['onmyoji'],
    '巫女': ['miko', 'shrine_maiden'],
    '神官': ['shinto_priest'],
    '僧人': ['monk', 'buddhist_monk'],
    '道士': ['taoist_priest'],
    '喇嘛': ['lama'],
    '活佛': ['living_buddha'],
    '菩萨': ['bodhisattva'],
    '佛陀': ['buddha'],
    '罗汉': ['arhat'],
    '金刚': ['vajra'],
    '天王': ['heavenly_king'],
    '阎王': ['king_of_hell'],
    '判官': ['judge_of_hell'],
    '无常': ['impermanent', 'ghost_messenger'],
    '黑白无常': ['black_and_white_impermanent'],
    '牛头马面': ['ox_head_and_horse_face'],
    '孟婆': ['meng_po'],
    '嫦娥': ['chang_e'],
    '后羿': ['hou_yi'],
    '女娲': ['nuwa'],
    '伏羲': ['fuxi'],
    '神农': ['shennong'],
    '黄帝': ['yellow_emperor'],
    '炎帝': ['flame_emperor'],
    '蚩尤': ['chiyou'],
    '刑天': ['xingtian'],
    '共工': ['gonggong'],
    '祝融': ['zhurong'],
    '后土': ['houtou'],
    '句芒': ['goumang'],
    '蓐收': ['rushou'],
    '玄冥': ['xuanming'],
    '强良': ['qiangliang'],
    '奢比尸': ['shebi_shi'],
    '天吴': ['tianwu'],
    '弇兹': ['yanzi'],
    '烛龙': ['torch_dragon'],
    '应龙': ['yinglong'],
    '青龙': ['azure_dragon'],
    '白虎': ['white_tiger'],
    '朱雀': ['vermilion_bird'],
    '玄武': ['black_tortoise'],
    '麒麟': ['qilin'],
    '貔貅': ['pixiu'],
    '饕餮': ['taotie'],
    '混沌': ['hundun'],
    '穷奇': ['qiongqi'],
    '梼杌': ['taowu'],
    '九尾狐': ['nine_tailed_fox', 'kyuubi'],
    '狐仙': ['fox_spirit'],
    '狸猫': ['tanuki'],
    '河童': ['kappa'],
    '天狗': ['tengu'],
    '河童': ['kappa'],
    '雪女': ['yuki_onna'],
    '雪男': ['yuki_otoko'],
    '雪童子': ['yukinko'],
    '冰女': ['ice_woman'],
    '冰男': ['ice_man'],
    '火女': ['fire_woman'],
    '火男': ['fire_man'],
    '风女': ['wind_woman'],
    '风男': ['wind_man'],
    '雷女': ['thunder_woman'],
    '雷男': ['thunder_man'],
    '电女': ['lightning_woman'],
    '电男': ['lightning_man'],
    '光女': ['light_woman'],
    '光男': ['light_man'],
    '暗女': ['dark_woman'],
    '暗男': ['dark_man'],
    '影女': ['shadow_woman'],
    '影男': ['shadow_man'],
    '梦女': ['dream_woman'],
    '梦男': ['dream_man'],
    '幻女': ['illusion_woman'],
    '幻男': ['illusion_man'],
    '镜女': ['mirror_woman'],
    '镜男': ['mirror_man'],
    '水女': ['water_woman'],
    '水男': ['water_man'],
    '木女': ['wood_woman'],
    '木男': ['wood_man'],
    '火女': ['fire_woman'],
    '火男': ['fire_man'],
    '土女': ['earth_woman'],
    '土男': ['earth_man'],
    '金女': ['metal_woman'],
    '金男': ['metal_man'],
    '花女': ['flower_woman'],
    '花男': ['flower_man'],
    '草女': ['grass_woman'],
    '草男': ['grass_man'],
    '树女': ['tree_woman'],
    '树男': ['tree_man'],
    '叶女': ['leaf_woman'],
    '叶男': ['leaf_man'],
    '果女': ['fruit_woman'],
    '果男': ['fruit_man'],
    '菜女': ['vegetable_woman'],
    '菜男': ['vegetable_man'],
    '谷女': ['grain_woman'],
    '谷男': ['grain_man'],
    '麦女': ['wheat_woman'],
    '麦男': ['wheat_man'],
    '稻女': ['rice_woman'],
    '稻男': ['rice_man'],
    '茶女': ['tea_woman'],
    '茶男': ['tea_man'],
    '酒女': ['wine_woman'],
    '酒男': ['wine_man'],
    '食女': ['food_woman'],
    '食男': ['food_man'],
    '饮女': ['drink_woman'],
    '饮男': ['drink_man'],
    '甜女': ['sweet_woman'],
    '甜男': ['sweet_man'],
    '苦女': ['bitter_woman'],
    '苦男': ['bitter_man'],
    '酸女': ['sour_woman'],
    '酸男': ['sour_man'],
    '辣女': ['spicy_woman'],
    '辣男': ['spicy_man'],
    '咸女': ['salty_woman'],
    '咸男': ['salty_man'],
    '鲜女': ['fresh_woman'],
    '鲜男': ['fresh_man'],
    '香女': ['fragrant_woman'],
    '香男': ['fragrant_man'],
    '臭女': ['stinky_woman'],
    '臭男': ['stinky_man'],
    '美女': ['beautiful_girl', 'pretty_girl'],
    '帅哥': ['handsome_boy', 'pretty_boy'],
    '美少女': ['beautiful_girl'],
    '美少年': ['bishounen'],
    '萝莉': ['loli', 'little_girl'],
    '正太': ['shota', 'little_boy'],
    '御姐': ['onee_san', 'mature_female'],
    '大叔': ['ojisan', 'middle_aged_man'],
    '阿姨': ['obasan', 'middle_aged_woman'],
    '老奶奶': ['old_woman', 'grandmother'],
    '老爷爷': ['old_man', 'grandfather'],
    '婴儿': ['baby', 'infant'],
    '幼儿': ['toddler'],
    '儿童': ['child', 'kid'],
    '少年': ['boy', 'young_man'],
    '少女': ['girl', 'young_woman'],
    '青年': ['youth', 'young_adult'],
    '中年': ['middle_aged'],
    '老年': ['elderly', 'old'],
    '人妖': ['trap', 'crossdresser'],
    '伪娘': ['crossdresser'],
    '扶她': ['futanari'],
    '双性': ['intersex'],
    '无性': ['genderless'],
    '中性': ['androgynous'],
    '人外': ['non_human'],
    '兽人': ['furry', 'anthropomorphic'],
    '毛茸茸': ['fluffy'],
    '毛绒绒': ['fluffy'],
    '可爱': ['cute', 'kawaii'],
    '萌': ['moe'],
    '帅': ['cool', 'handsome'],
    '美': ['beautiful', 'pretty'],
    '性感': ['sexy', 'erotic'],
    '色情': ['explicit', 'nsfw'],
    '暴力': ['violent', 'gore'],
    '血腥': ['gore', 'blood'],
    '恐怖': ['horror', 'scary'],
    '惊悚': ['thriller'],
    '悬疑': ['mystery'],
    '推理': ['detective', 'mystery'],
    '科幻': ['sci_fi', 'science_fiction'],
    '奇幻': ['fantasy'],
    '魔幻': ['magic', 'magical'],
    '玄幻': ['xianxia', 'cultivation'],
    '仙侠': ['xianxia'],
    '武侠': ['wuxia', 'martial_arts'],
    '修仙': ['cultivation'],
    '修真': ['cultivation'],
    '练功': ['training'],
    '升级': ['level_up'],
    '打怪': ['monster_fighting'],
    '刷副本': ['dungeon_crawling'],
    '组队': ['party', 'team'],
    '公会': ['guild'],
    '联盟': ['alliance'],
    '帮派': ['gang', 'faction'],
    '门派': ['sect', 'school'],
    '宗门': ['sect'],
    '家族': ['family', 'clan'],
    '种族': ['race', 'species'],
    '人类': ['human'],
    '精灵': ['elf'],
    '矮人': ['dwarf'],
    '兽人': ['orc', 'furry'],
    '半兽人': ['half_orc'],
    '半精灵': ['half_elf'],
    '半人马': ['centaur'],
    '人马': ['centaur'],
    '人马': ['satyr'],
    '牛头人': ['minotaur'],
    '羊头人': ['faun'],
    '鸟人': ['harpy', 'bird_person'],
    '鱼人': ['mermaid', 'fishman'],
    '人鱼': ['mermaid'],
    '美人鱼': ['mermaid'],
    '鲛人': ['mermaid'],
    '龙人': ['dragon_person', 'dragonoid'],
    '蛇人': ['lamia', 'naga'],
    '蜘蛛人': ['arachne'],
    '昆虫人': ['insectoid'],
    '植物人': ['plant_person', 'dryad'],
    '树人': ['treant', 'ent'],
    '石头人': ['golem'],
    '泥人': ['clay_golem'],
    '铁人': ['iron_golem'],
    '机器人': ['android', 'robot'],
    '生化人': ['cyborg'],
    '改造人': ['cyborg'],
    '合成人': ['synthetic_human'],
    '克隆人': ['clone'],
    '复制人': ['clone'],
    '分身': ['clone', 'double'],
    '替身': ['stand', 'substitute'],
    '幽灵': ['ghost', 'spirit'],
    '灵魂': ['soul'],
    '亡灵': ['undead'],
    '死灵': ['necromancer'],
    '僵尸': ['zombie'],
    '丧尸': ['zombie'],
    '活死人': ['living_dead'],
    '行尸走肉': ['walking_dead'],
    '木乃伊': ['mummy'],
    '骷髅': ['skeleton'],
    '骸骨': ['skeleton'],
    '白骨': ['skeleton'],
    '鬼': ['ghost'],
    '妖': ['demon', 'monster'],
    '魔': ['demon', 'devil'],
    '仙': ['immortal', 'fairy'],
    '神': ['god', 'deity'],
    '佛': ['buddha'],
    '菩萨': ['bodhisattva'],
    '罗汉': ['arhat'],
    '金刚': ['vajra'],
    '天王': ['heavenly_king'],
    '阎王': ['king_of_hell'],
    '判官': ['judge'],
    '无常': ['impermanent'],
    '孟婆': ['meng_po'],
    '嫦娥': ['chang_e'],
    '后羿': ['hou_yi'],
    '女娲': ['nuwa'],
    '伏羲': ['fuxi'],
    '神农': ['shennong'],
    '黄帝': ['yellow_emperor'],
    '炎帝': ['flame_emperor'],
    '蚩尤': ['chiyou'],
    '刑天': ['xingtian'],
    '共工': ['gonggong'],
    '祝融': ['zhurong'],
    '后土': ['houtou'],
    '句芒': ['goumang'],
    '蓐收': ['rushou'],
    '玄冥': ['xuanming'],
    '强良': ['qiangliang'],
    '奢比尸': ['shebi_shi'],
    '天吴': ['tianwu'],
    '弇兹': ['yanzi'],
    '烛龙': ['torch_dragon'],
    '应龙': ['yinglong'],
    '青龙': ['azure_dragon'],
    '白虎': ['white_tiger'],
    '朱雀': ['vermilion_bird'],
    '玄武': ['black_tortoise'],
    '麒麟': ['qilin'],
    '貔貅': ['pixiu'],
    '饕餮': ['taotie'],
    '混沌': ['hundun'],
    '穷奇': ['qiongqi'],
    '梼杌': ['taowu'],
    '九尾狐': ['nine_tailed_fox'],
    '狐仙': ['fox_spirit'],
    '狸猫': ['tanuki'],
    '河童': ['kappa'],
    '天狗': ['tengu'],
    '雪女': ['yuki_onna'],
    '巫女': ['miko'],
    '阴阳师': ['onmyoji'],
    '忍者': ['ninja'],
    '武士': ['samurai'],
    '艺妓': ['geisha'],
    '花魁': ['oiran'],
    '太夫': ['tayuu'],
    '游女': ['yujo'],
    '娼妓': ['prostitute'],
    '妓女': ['prostitute'],
    '妓男': ['male_prostitute'],
    '牛郎': ['host'],
    '男公关': ['host'],
    '陪酒女': ['hostess'],
    '陪酒男': ['male_hostess'],
    '酒吧': ['bar', 'pub', 'izakaya'],
    '夜总会': ['nightclub'],
    '俱乐部': ['club'],
    '会所': ['clubhouse'],
    '会所': ['spa'],
    '按摩': ['massage'],
    '推拿': ['massage'],
    '针灸': ['acupuncture'],
    '拔罐': ['cupping'],
    '刮痧': ['gua_sha'],
    '艾灸': ['moxibustion'],
    '中药': ['chinese_medicine'],
    '西药': ['western_medicine'],
    '药': ['medicine', 'potion'],
    '丹': ['pill', 'elixir'],
    '药丸': ['pill'],
    '药散': ['powder'],
    '药汤': ['decoction'],
    '药酒': ['medicinal_wine'],
    '毒药': ['poison'],
    '解毒药': ['antidote'],
    '恢复药': ['recovery_item'],
    '体力药': ['stamina_potion'],
    '魔力药': ['mana_potion'],
    '经验药': ['exp_potion'],
    '升级药': ['level_up_item'],
    '强化药': ['enhancement_item'],
    'buff 药': ['buff_item'],
    'debuff 药': ['debuff_item'],
    '诅咒药': ['curse_item'],
    '封印药': ['seal_item'],
    '解封印药': ['unseal_item'],
    '复活药': ['revival_item'],
    '不死药': ['immortality_elixir'],
    '长生药': ['immortality_elixir'],
    '仙丹': ['immortality_elixir'],
    '灵丹': ['spirit_pill'],
    '金丹': ['golden_pill'],
    '元婴': ['nascent_soul'],
    '化神': ['soul_transformation'],
    '合体': ['body_integration'],
    '大乘': ['great_vehicle'],
    '渡劫': ['tribulation'],
    '飞升': ['ascension'],
    '成仙': ['become_immortal'],
    '成佛': ['become_buddha'],
    '成神': ['become_god'],
    '成魔': ['become_demon'],
    '成妖': ['become_demon'],
    '成精': ['become_spirit'],
    '化形': ['shapeshift'],
    '变形': ['transformation'],
    '变身': ['transformation'],
    '换装': ['outfit_change'],
    '换衣': ['outfit_change'],
    '更衣': ['outfit_change'],
    '穿衣服': ['dressing'],
    '脱衣服': ['undressing'],
    '裸体': ['nude', 'naked'],
    '半裸': ['partially_nude'],
    '暴露': ['revealing_clothes'],
    '性感': ['sexy'],
    '诱惑': ['seductive'],
    '挑逗': ['teasing'],
    '调情': ['flirting'],
    '接吻': ['kissing'],
    '拥抱': ['hugging'],
    '牵手': ['holding_hands'],
    '依偎': ['snuggling'],
    '亲吻': ['kissing'],
    '舌吻': ['french_kiss'],
    '咬': ['biting'],
    '舔': ['licking'],
    '吸': ['sucking'],
    '吮': ['sucking'],
    '含': ['holding_in_mouth'],
    '吞': ['swallowing'],
    '咽': ['swallowing'],
    '吐': ['spitting', 'vomiting'],
    '呕': ['vomiting'],
    '咳': ['coughing'],
    '喘': ['panting'],
    '呼吸': ['breathing'],
    '心跳': ['heartbeat'],
    '脉搏': ['pulse'],
    '血液': ['blood'],
    '流血': ['bleeding'],
    '伤口': ['wound', 'injury'],
    '伤疤': ['scar'],
    '疤痕': ['scar'],
    '绷带': ['bandage'],
    '创可贴': ['bandaid'],
    '纱布': ['gauze'],
    '药水': ['antiseptic'],
    '消毒水': ['antiseptic'],
    '酒精': ['alcohol'],
    '碘酒': ['iodine'],
    '红药水': ['red_medicine'],
    '紫药水': ['purple_medicine'],
    '药膏': ['ointment'],
    '药贴': ['medicated_patch'],
    '膏药': ['medicated_patch'],
    '热敷': ['hot_compress'],
    '冷敷': ['cold_compress'],
    '冰敷': ['ice_pack'],
    '按摩': ['massage'],
    '推拿': ['massage'],
    '针灸': ['acupuncture'],
    '拔罐': ['cupping'],
    '刮痧': ['gua_sha'],
    '艾灸': ['moxibustion'],
    '中药': ['chinese_medicine'],
    '西药': ['western_medicine'],
    '药': ['medicine'],
    '丹': ['pill'],
    '药丸': ['pill'],
    '药散': ['powder'],
    '药汤': ['decoction'],
    '药酒': ['medicinal_wine'],
    '毒药': ['poison'],
    '解毒药': ['antidote'],
    '恢复药': ['recovery_item'],
    '体力药': ['stamina_potion'],
    '魔力药': ['mana_potion'],
    '经验药': ['exp_potion'],
    '升级药': ['level_up_item'],
    '强化药': ['enhancement_item'],
    'buff 药': ['buff_item'],
    'debuff 药': ['debuff_item'],
    '诅咒药': ['curse_item'],
    '封印药': ['seal_item'],
    '解封印药': ['unseal_item'],
    '复活药': ['revival_item'],
    '不死药': ['immortality_elixir'],
    '长生药': ['immortality_elixir'],
    '仙丹': ['immortality_elixir'],
    '灵丹': ['spirit_pill'],
    '金丹': ['golden_pill'],
    '元婴': ['nascent_soul'],
    '化神': ['soul_transformation'],
    '合体': ['body_integration'],
    '大乘': ['great_vehicle'],
    '渡劫': ['tribulation'],
    '飞升': ['ascension'],
    '成仙': ['become_immortal'],
    '成佛': ['become_buddha'],
    '成神': ['become_god'],
    '成魔': ['become_demon'],
    '成妖': ['become_demon'],
    '成精': ['become_spirit'],
    '化形': ['shapeshift'],
    '变形': ['transformation'],
    '变身': ['transformation'],
    '换装': ['outfit_change'],
    '换衣': ['outfit_change'],
    '更衣': ['outfit_change'],
    '穿衣服': ['dressing'],
    '脱衣服': ['undressing'],
    '裸体': ['nude', 'naked'],
    '半裸': ['partially_nude'],
    '暴露': ['revealing_clothes'],
    '性感': ['sexy'],
    '诱惑': ['seductive'],
    '挑逗': ['teasing'],
    '调情': ['flirting'],
    '接吻': ['kissing'],
    '拥抱': ['hugging'],
    '牵手': ['holding_hands'],
    '依偎': ['snuggling'],
    '亲吻': ['kissing'],
    '舌吻': ['french_kiss'],
    '咬': ['biting'],
    '舔': ['licking'],
    '吸': ['sucking'],
    '吮': ['sucking'],
    '含': ['holding_in_mouth'],
    '吞': ['swallowing'],
    '咽': ['swallowing'],
    '吐': ['spitting', 'vomiting'],
    '呕': ['vomiting'],
    '咳': ['coughing'],
    '喘': ['panting'],
    '呼吸': ['breathing'],
    '心跳': ['heartbeat'],
    '脉搏': ['pulse'],
    '血液': ['blood'],
    '流血': ['bleeding'],
    '伤口': ['wound', 'injury'],
    '伤疤': ['scar'],
    '疤痕': ['scar'],
    '绷带': ['bandage'],
    '创可贴': ['bandaid'],
    '纱布': ['gauze'],
    '药水': ['antiseptic'],
    '消毒水': ['antiseptic'],
    '酒精': ['alcohol'],
    '碘酒': ['iodine'],
    '红药水': ['red_medicine'],
    '紫药水': ['purple_medicine'],
    '药膏': ['ointment'],
    '药贴': ['medicated_patch'],
    '膏药': ['medicated_patch'],
    '热敷': ['hot_compress'],
    '冷敷': ['cold_compress'],
    '冰敷': ['ice_pack'],
};

// 快速匹配函数
function quickMatchChinese(query) {
    const matchedTags = new Map();
    const queryLower = query.toLowerCase();
    
    // 遍历索引，查找匹配的中文关键词
    for (const [keyword, tags] of Object.entries(CHINESE_INDEX)) {
        if (queryLower.includes(keyword)) {
            tags.forEach(tag => {
                if (!matchedTags.has(tag)) {
                    matchedTags.set(tag, {
                        name: tag,
                        source: 'chinese_index',
                        reason: `匹配关键词：${keyword}`,
                        confidence: 1.0
                    });
                }
            });
        }
    }
    
    return Array.from(matchedTags.values());
}

// 导出索引和函数
module.exports = { CHINESE_INDEX, quickMatchChinese };
